# Form implementation generated from reading ui file 'UI\Network\Host\set_host_args.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qdarktheme.qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 308)
        font = QtGui.QFont()
        font.setPointSize(20)
        Dialog.setFont(font)
        self.sysButton = QtWidgets.QPushButton(parent=Dialog)
        self.sysButton.setGeometry(QtCore.QRect(130, 210, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sysButton.setFont(font)
        self.sysButton.setAutoDefault(False)
        self.sysButton.setObjectName("sysButton")
        self.netButton = QtWidgets.QPushButton(parent=Dialog)
        self.netButton.setGeometry(QtCore.QRect(130, 120, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.netButton.setFont(font)
        self.netButton.setAutoDefault(False)
        self.netButton.setObjectName("netButton")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_name.setGeometry(QtCore.QRect(160, 40, 241, 51))
        self.lineEdit_name.setObjectName("lineEdit_name")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sysButton.setText(_translate("Dialog", "编辑计算属性"))
        self.netButton.setText(_translate("Dialog", "编辑网络属性"))
        self.label.setText(_translate("Dialog", "名称："))
