# Form implementation generated from reading ui file 'UI\Network\edit_switch_netargs_tsn.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qdarktheme.qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(858, 518)
        self.applyButton = QtWidgets.QPushButton(parent=Dialog)
        self.applyButton.setGeometry(QtCore.QRect(380, 440, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.applyButton.setFont(font)
        self.applyButton.setAutoDefault(False)
        self.applyButton.setObjectName("applyButton")
        self.tableWidget_netargs = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget_netargs.setGeometry(QtCore.QRect(60, 110, 751, 311))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tableWidget_netargs.setFont(font)
        self.tableWidget_netargs.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tableWidget_netargs.setStyleSheet("")
        self.tableWidget_netargs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget_netargs.setObjectName("tableWidget_netargs")
        self.tableWidget_netargs.setColumnCount(1)
        self.tableWidget_netargs.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget_netargs.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_netargs.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tableWidget_netargs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tableWidget_netargs.setItem(0, 0, item)
        self.tableWidget_netargs.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_netargs.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget_netargs.horizontalHeader().setHighlightSections(True)
        self.tableWidget_netargs.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_netargs.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget_netargs.verticalHeader().setStretchLastSection(False)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_name.setGeometry(QtCore.QRect(230, 40, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.applyButton.setText(_translate("Dialog", "应用"))
        item = self.tableWidget_netargs.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "转发速率（Mbps）"))
        item = self.tableWidget_netargs.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "tsn队列信息（json）"))
        item = self.tableWidget_netargs.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "值"))
        __sortingEnabled = self.tableWidget_netargs.isSortingEnabled()
        self.tableWidget_netargs.setSortingEnabled(False)
        self.tableWidget_netargs.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog", "名称："))
