# Form implementation generated from reading ui file 'UI\Network\edit_link_args.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qdarktheme.qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 308)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 221, 61))
        self.label.setObjectName("label")
        self.applyButton = QtWidgets.QPushButton(parent=Dialog)
        self.applyButton.setGeometry(QtCore.QRect(210, 210, 141, 41))
        self.applyButton.setAutoDefault(False)
        self.applyButton.setObjectName("applyButton")
        self.lineEdit_bw = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_bw.setGeometry(QtCore.QRect(290, 110, 211, 51))
        self.lineEdit_bw.setObjectName("lineEdit_bw")
        self.lineEdit_bw_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_bw_2.setGeometry(QtCore.QRect(290, 30, 211, 51))
        self.lineEdit_bw_2.setText("")
        self.lineEdit_bw_2.setObjectName("lineEdit_bw_2")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 141, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "链路带宽(Mbps)："))
        self.applyButton.setText(_translate("Dialog", "应用"))
        self.lineEdit_bw.setText(_translate("Dialog", "100"))
        self.label_2.setText(_translate("Dialog", "名称："))
