# Form implementation generated from reading ui file 'UI\Network\network_editor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qdarktheme.qtpy import QtCore, QtGui, QtWidgets
from scene import GraphicScene
from view import GraphicView
from resources import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(916, 692)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.infoList = QtWidgets.QTreeWidget(parent=Form)
        self.infoList.setColumnCount(0)
        self.infoList.setObjectName("infoList")
        self.verticalLayout_3.addWidget(self.infoList)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.add = QtWidgets.QGridLayout()
        self.add.setObjectName("add")
        self.global_setting = QtWidgets.QPushButton(parent=Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\Network\\../../img/MaterialSymbolsSettings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.global_setting.setIcon(icon)
        self.global_setting.setObjectName("global_setting")
        self.add.addWidget(self.global_setting, 2, 1, 1, 1)
        self.add_switch = QtWidgets.QPushButton(parent=Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI\\Network\\../../img/MdiSwitch.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_switch.setIcon(icon1)
        self.add_switch.setObjectName("add_switch")
        self.add.addWidget(self.add_switch, 0, 1, 1, 1)
        self.add_line = QtWidgets.QPushButton(parent=Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI\\Network\\../../img/WhhLine.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_line.setIcon(icon2)
        self.add_line.setObjectName("add_line")
        self.add.addWidget(self.add_line, 2, 0, 1, 1)
        self.add_host = QtWidgets.QPushButton(parent=Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI\\Network\\../../img/Host.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_host.setIcon(icon3)
        self.add_host.setObjectName("add_host")
        self.add.addWidget(self.add_host, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.add)
        self.run = QtWidgets.QPushButton(parent=Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI\\Network\\fe/img/播放按钮.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.run.setIcon(icon4)
        self.run.setObjectName("run")
        self.verticalLayout_3.addWidget(self.run)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = GraphicView(GraphicScene(Form) , parent=Form)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "网络结构"))
        self.label_2.setText(_translate("Form", "添加"))
        self.global_setting.setText(_translate("Form", "全局设置"))
        self.add_switch.setText(_translate("Form", "交换机"))
        self.add_line.setText(_translate("Form", "连线"))
        self.add_host.setText(_translate("Form", "主机"))
        self.run.setText(_translate("Form", "运行仿真"))
