# Form implementation generated from reading ui file 'UI\new_project.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qdarktheme.qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 70, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(290, 210, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.applyButton = QtWidgets.QPushButton(parent=Dialog)
        self.applyButton.setGeometry(QtCore.QRect(260, 360, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.applyButton.setFont(font)
        self.applyButton.setAutoDefault(False)
        self.applyButton.setObjectName("applyButton")
        self.directoryButton = QtWidgets.QPushButton(parent=Dialog)
        self.directoryButton.setGeometry(QtCore.QRect(290, 80, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.directoryButton.setFont(font)
        self.directoryButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.directoryButton.setAutoDefault(False)
        self.directoryButton.setObjectName("directoryButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "选择工程所在路径："))
        self.label_2.setText(_translate("Dialog", "工程名称："))
        self.lineEdit.setText(_translate("Dialog", "project1"))
        self.applyButton.setText(_translate("Dialog", "确定"))
        self.directoryButton.setText(_translate("Dialog", "C:/"))
